<?php

namespace backend\models;

use Yii;
use yii\behaviors\TimestampBehavior;
/**
 * This is the model class for table "{{%tags_info}}".
 *
 * @property string $id
 * @property string $subtag_num 关联下一级子标签数量
 * @property string $phon_num 关联手机号码数量
 */
class TagsInfo extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tags_info}}';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    # 创建之前
                    self::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    # 修改之前
                    self::EVENT_BEFORE_UPDATE => ['updated_at']
                ],
                #设置默认值
                'value' => time()
            ]
        ];
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subtag_num', 'phon_num'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'subtag_num' => '关联下一级子标签数量',
            'phon_num' => '关联手机号码数量',
        ];
    }

    /**
     * @inheritdoc
     * @return TagsInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TagsInfoQuery(get_called_class());
    }


    public function save($runValidation = true, $attributeNames = null)
    {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

}
