<?php

namespace backend\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%tasks}}".
 *
 * @property string $id
 * @property string $title 标题
 * @property string $info 推送内容
 * @property int $age 年龄段
 * @property int $sex 性别
 * @property string $send_num 发送数目
 * @property string $send_end_num 已发送条数
 * @property int $phone_num 关联手机号码数量
 * @property int $subtag_num 关联下一级子标签数量
 * @property int $created_at 创建时间
 * @property int $updated_at 更新时间
 * @property string $desc 备注
 * @property int $status 状态
 */
class Tasks extends \yii\db\ActiveRecord
{
    private $areas;
    private $tags;

    public static function statusList()
    {
        return [
            -1 => '未执行',
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tasks}}';
    }

    public function getTags()
    {
        return $this->tags;
    }


    public function setTags($tags)
    {
        return $this->tags = $tags;
    }

    public function getAreas()
    {
        return $this->areas;
    }

    public function setAreas($areas)
    {
        return $this->areas = $areas;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['info', 'tags', 'areas'], 'string'],
            [['title', 'info', 'age', 'sex', 'send_num', 'tags', 'areas'], 'required'],
            [['age', 'sex', 'send_num', 'send_end_num', 'phone_num', 'subtag_num', 'created_at', 'updated_at', 'status'], 'integer'],
            [['send_num', 'send_end_num', 'phone_num', 'subtag_num'], 'default', 'value' => 0],
            [['title', 'desc'], 'string', 'max' => 255],
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    # 创建之前
                    self::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    # 修改之前
                    self::EVENT_BEFORE_UPDATE => ['updated_at']
                ],
                #设置默认值
                'value' => time()
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'info' => '推送内容',
            'age' => '年龄段',
            'sex' => '性别',
            'tags' => '标签',
            'areas' => '地区',
            'send_num' => '发送数目',
            'send_end_num' => '已发送条数',
            'phone_num' => '关联手机号码数量',
            'subtag_num' => '关联下一级子标签数量',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'desc' => '备注',
            'status' => '状态',
        ];
    }

    /**
     * @inheritdoc
     * @return TasksQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TasksQuery(get_called_class());
    }

    public function beforeValidate()
    {

        $_sex = $this->sex;
        if ($_sex) {
            if (is_array($_sex)) {
                $sex = array_intersect($_sex, array_keys(PhoneUsers::getSexList()));
                $sex = PhoneUsers::getSexAll($sex);
                if (empty($sex)) {
                    $this->addError('sex', '性别非法');
                    return false;
                }
                $this->sex = $sex;
            } else if (!intval($_sex) || !($_sex & PhoneUsers::getSexAll())) {
                $this->addError('sex', '性别非法');
                return false;
            }
        }

        $_age = $this->age;
        if($_age){
            if (is_array($_age)) {
                $age = array_intersect($_age, array_keys(PhoneUsers::getAgeList()));
                $age = PhoneUsers::getAgeAll($age);
                if (empty($age)) {
                    $this->addError('age', '年龄段非法');
                    return false;
                }
                $this->age = $age;
            } else if (!intval($_age) || !($_age & PhoneUsers::getAgeAll())) {
                $this->addError('age', '年龄段非法');
                return false;
            }
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if (!empty($this->tags)) {
            $tags = empty($this->tags) ? '' : $this->tags;
            $tags = explode(',', $tags);
            sort($tags);
            foreach ($tags as $tagId) {
                $tasksTagsJoinModel = new TasksTagsJoin();
                $tasksTagsJoinModel->setAttribute('tasks_id', $this->id);
                $tasksTagsJoinModel->setAttribute('tags_id', $tagId);
                $tasksTagsJoinModel->save();
            }

        }
        if (!empty($this->areas)) {
            $tags = empty($this->areas) ? '' : $this->areas;
            $tags = explode(',', $tags);
            sort($tags);
            foreach ($tags as $tagId) {
                $tasksTagsJoinModel = new TasksAreasJoin();
                $tasksTagsJoinModel->setAttribute('tasks_id', $this->id);
                $tasksTagsJoinModel->setAttribute('areas_id', $tagId);
                $tasksTagsJoinModel->save();
            }
        }

    }


}
